apiVersion: v1
kind: ReplicationController
metadata: 
    name: rcweb1
spec:
    replicas: 2
    selector:
        env: dev
        dc: india
        app: webserver
    template: 
        metadata:
            name: mypod1
            labels:
                env: dev
                dc: india
                app: webserver
        spec:
            containers:
              - name: "mycon1"
                image: "vimal13/apache-webserver-php"