apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: rsweb1
spec:
    replicas: 2
    selector:
        matchLabels:
            env: dev
            dc: india
            app: webserver
        matchExpression:
           - {key: env, operator: In, values: [ dev ]}
           - {key: dc, operator: In, values: [ india ]}
           - {key: app, operator: In, values: [ webserver]}
    template: 
        metadata:
            name: mypod1
            labels:
                env: dev
                dc: india
                app: webserver
        spec:
            containers:
              - name: "mycon1"
                image: "vimal13/apache-webserver-php"
                env: 
                  - name: x
                    values: shivam